# -*- coding: utf-8 -*-
"""Accident data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17P4DZt3V9Iopm1qeqYz4f20k5xvFIcvs

# Libraries
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import os
import gc
from statsmodels.tsa.seasonal import seasonal_decompose

sns.set(style="whitegrid")

"""# Load Dataset"""

from google.colab import drive
drive.mount('/content/drive')

# =============================================================================
# 1️⃣ Load All Datasets Efficiently
# =============================================================================

def load_csv(path):
    """Load a CSV with accident_index as string to avoid type issues."""
    return pd.read_csv(
        path,
        low_memory=False,
        dtype={'accident_index': 'string'}
    )

print("Loading files...")
df_main      = load_csv('/content/drive/MyDrive/severity_analysis.csv')
df_spatial   = load_csv('/content/drive/MyDrive/spatial_analysis.csv')
df_demographic = load_csv('/content/drive/MyDrive/demographic_analysis.csv')
df_temporal  = load_csv('/content/drive/MyDrive/temporal_analysis.csv')
df_risk      = load_csv('/content/drive/MyDrive/risk_factors_analysis.csv')
print("All files loaded successfully.")

# =============================================================================
# 2️⃣ Add Sequence Numbers to Casualty‑Level Files
# =============================================================================

casualty_dfs = [df_main, df_spatial, df_demographic, df_risk]
for df in casualty_dfs:
    df['seq'] = df.groupby('accident_index', observed=True).cumcount()

print("Sequence columns added to all casualty‑level dataframes.")

# =============================================================================
# 3️⃣ Verify Row Counts Are Identical Across All Casualty Files
# =============================================================================

ref_counts = df_main.groupby('accident_index', observed=True).size()
all_match = True
for name, df in zip(['spatial', 'demographic', 'risk'], casualty_dfs[1:]):
    counts = df.groupby('accident_index', observed=True).size()
    if not ref_counts.equals(counts):
        print(f"⚠️  Row counts differ in {name} file!")
        all_match = False
if all_match:
    print("✅ All casualty files have identical row counts per accident.")

# =============================================================================
# 4️⃣ Merge All Casualty‑Level Files (Left Join on accident_index & seq)
# =============================================================================

# Start with the main file and merge others sequentially
df_casualty = df_main.copy()
for df in casualty_dfs[1:]:
    df_casualty = df_casualty.merge(
        df,
        on=['accident_index', 'seq'],
        how='left',
        suffixes=('', '_dup')          # avoid duplicate column warnings
    )
    # Drop any duplicate columns that may have appeared (like casualty_age from risk)
    # We'll keep the first occurrence (from main) and drop the rest.
    dup_cols = [c for c in df_casualty.columns if c.endswith('_dup')]
    df_casualty.drop(columns=dup_cols, inplace=True, errors='ignore')

print("Casualty‑level merge complete. Shape:", df_casualty.shape)

# =============================================================================
# 5️⃣ Validate Alignment (Compare casualty_age from main and demographic)
# =============================================================================

if 'casualty_age' in df_casualty.columns and 'casualty_age' in df_main.columns:
    # The merge kept the original from df_main; demographic may have been renamed
    # We already dropped duplicates, but we can still check:
    sample = df_casualty[['casualty_age', 'age_band_of_casualty']].dropna().sample(min(1000, len(df_casualty)))
    # age_band_of_casualty should be consistent with casualty_age; we can just print a few rows
    print("Sample alignment (casualty_age vs age_band):")
    print(sample.head(10))
else:
    print("Skipping age validation – required columns not found.")

# =============================================================================
# 6️⃣ Merge Accident‑Level Temporal Data
# =============================================================================

df_temporal = df_temporal.drop_duplicates(subset='accident_index')
df_final = df_casualty.merge(df_temporal, on='accident_index', how='left')
print("Temporal data merged. Shape:", df_final.shape)

# =============================================================================
# 7️⃣ Clean Up and Remove Temporary Columns
# =============================================================================

# Free memory
del df_casualty, df_temporal, df_main, df_spatial, df_demographic, df_risk
gc.collect()

# Drop the sequence column (no longer needed)
if 'seq' in df_final.columns:
    df_final.drop(columns=['seq'], inplace=True)

print("Final data shape:", df_final.shape)
print("Total columns:", len(df_final.columns))

"""We loaded this CSV to obtain vehicle type (car, motorcycle, etc.) for the Car Details section, and merged it with accident severity so we can analyze how vehicle type relates to accident outcomes.

# Understand the data
"""

df_final.head()

df_final.columns

df_final.describe()

df_final.dtypes

"""# Data Cleaning

## Check Duplicates
"""

print(f"Number of duplicate rows in df_final: {df_final.duplicated().sum()}")

print("Columns in df_final with duplicate values (i.e., not all unique):")
duplicate_columns = []
for col in df_final.columns:
    if df_final[col].nunique() < len(df_final):
        duplicate_columns.append(col)

if duplicate_columns:
    for col_name in duplicate_columns:
        print(f"- {col_name}")
else:
    print("No columns found with duplicate values (all values unique within each column).")

# Show duplicate rows (first 10)
dupes = df_final[df_final.duplicated(keep=False)].sort_values('accident_index')
dupes.head(10)

"""## Drop Duplicates"""

# 1. Drop useless coordinate columns (only if they exist)
for col in ['longitude', 'latitude']:
    if col in df_final.columns:
        df_final = df_final.drop(columns=[col])
        print(f"Dropped {col}")
    else:
        print(f"{col} not present – skipping.")

# 2. Drop duplicate accident_severity column (keep one)
if 'accident_severity_y' in df_final.columns:
    df_final = df_final.drop(columns=['accident_severity_y'])
    df_final = df_final.rename(columns={'accident_severity_x': 'accident_severity'})
    print("Cleaned accident_severity columns.")
else:
    print("accident_severity_y not found – maybe already cleaned.")

# 3. Verify day_of_week is now populated
print("\nChecking day_of_week:")
print("Missing values:", df_final['day_of_week'].isna().sum())
print("First 10 values:")
print(df_final['day_of_week'].head(10))

# 4. (Optional) Drop enhanced columns if you don't need them – uncomment if desired
# for col in ['enhanced_severity_collision', 'enhanced_casualty_severity']:
#     if col in df_final.columns:
#         df_final = df_final.drop(columns=[col])

# 5. Check final shape
print("\nFinal clean shape:", df_final.shape)

df_final = df_final.drop_duplicates()
print("Shape after dropping exact duplicates:", df_final.shape)

"""## Verify"""

df_final.duplicated().sum()

"""## Missing Values Analysis"""

df_final.isna().sum()

missing_percentage = (df_final.isnull().sum() / len(df_final)) * 100
missing_percentage = missing_percentage[missing_percentage > 0].sort_values(ascending=False)
print("Percentage of missing values in df_final:")
print(missing_percentage)

# Store original row count for reference
original_rows = len(df_final)
print(f"Rows before handling missing: {original_rows}")

# 1. Drop rows missing casualty_age (1.88%)
df_final = df_final.dropna(subset=['casualty_age'])
print(f"After dropping missing casualty_age: {len(df_final)} rows")

# 2. Drop rows missing OS grid references (0.012%)
df_final = df_final.dropna(subset=['location_easting_osgr', 'location_northing_osgr'])
print(f"After dropping missing OS grid: {len(df_final)} rows")

# 3. Verify missing values again
print("\nMissing values after cleaning:")
print(df_final.isnull().sum())

# 4. Check final shape
print(f"\nFinal clean shape: {df_final.shape}")

# Subset for driver casualties only
drivers = df_final[df_final['driver_age'].notna()].copy()
print(f"Driver records: {len(drivers)} ({len(drivers)/len(df_final)*100:.1f}% of casualties)")

"""We dropped very few rows with missing casualty age (only 2%) because age is important for understanding who gets hurt. We also removed a tiny number of rows missing location coordinates so our maps would be accurate. Driver age was missing for many people who weren't drivers, so we kept those rows and just separated them later when analyzing drivers. This way we kept almost all our data while making sure it's clean and ready for analysis.

# Exploratory Data Analysis (EDA)

## Temporal Analysis

In the time-based analysis, we examined when accidents occur by looking at different time factors. The following plots were created to understand patterns:

Accidents by Hour – to identify peak times, such as morning and evening rush hours.

Accidents by Time of Day – grouping hours into Night, Morning, Afternoon, and Evening for a broader view.

Accidents by Day of the Week – to compare weekdays with weekends.

Weekend vs Weekday – a simple comparison of total accidents.

Accidents by Season – to check for seasonal variations.

Accidents by Year – to observe trends over multiple years.

Rush Hour vs Non-Rush Hour – focusing on defined rush hour periods to see if accident counts increase.

From these plots, clear patterns emerged: more accidents occur during afternoon rush hours, fewer happen on weekends, and some seasonal trends are visible. This analysis provides a detailed understanding of the timing of accidents.

## Setup
"""

# Ensure we work on a copy to avoid warnings
df = df_final.copy()

"""# Temp"""

def time_bin(hour):
    if 0 <= hour < 6:
        return 'Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'
df['time_of_day'] = df['hour'].apply(time_bin)
df['rush_hour'] = df['hour'].apply(lambda x: 1 if (7 <= x <= 9) or (16 <= x <= 19) else 0)

# Add is_weekend column to df
df['is_weekend'] = df['day_of_week'].isin(['Sat', 'Sun']).astype(int)

print("New columns added:")
print(df[['is_weekend', 'time_of_day', 'rush_hour']].head())

# ---------------------------
# Chunk 2: Accident-level DataFrame
# ---------------------------
accidents = df.drop_duplicates(subset='accident_index').copy()
print("Unique day values:", accidents['day_of_week'].unique())
# If days are full names, convert: accidents['day_of_week'] = accidents['day_of_week'].str[:3]

# ---------------------------
# Chunk 3: Set categorical orders
# ---------------------------
weekday_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
accidents['day_of_week'] = pd.Categorical(accidents['day_of_week'],
                                          categories=weekday_order,
                                          ordered=True)
time_order = ['Night', 'Morning', 'Afternoon', 'Evening']
accidents['time_of_day'] = pd.Categorical(accidents['time_of_day'],
                                          categories=time_order,
                                          ordered=True)
# Ensure date is datetime
accidents['date'] = pd.to_datetime(accidents['date'])
accidents['month'] = accidents['date'].dt.month

"""###  Accidents by Hour"""

# -------------------------------------------------
# 1. Accidents by Hour of Day
# -------------------------------------------------
# Why: To identify the hours with highest accident frequency.
plt.figure(figsize=(12,5))
order = sorted(accidents['hour'].dropna().unique())
sns.countplot(x='hour', data=accidents, order=order, color='steelblue')
plt.title('Accidents by Hour of Day')
plt.xlabel('Hour (24h)')
plt.ylabel('Accident Count')
plt.show()

"""### Accidents by Time of Day"""

# -------------------------------------------------
# 2. Accidents by Time of Day (Night, Morning, Afternoon, Evening)
# -------------------------------------------------
# Why: Group hours into broader periods to see overall patterns.
time_order = ['Night', 'Morning', 'Afternoon', 'Evening']
# Ensure categorical ordering (already set in your step 3)
plt.figure(figsize=(8,5))
sns.countplot(x='time_of_day', data=accidents, color='steelblue')
plt.title('Accidents by Time of Day')
plt.xlabel('Time of Day')
plt.ylabel('Accident Count')
plt.show()

"""Most accidents happen in the afternoon and evening, when traffic is heaviest. Nighttime has the fewest accidents because fewer people are on the roads. This shows that rush hours are the most dangerous times for driving.

### Accidents by Day of Week
"""

# Why: Understand how accident frequency varies across the week.
weekday_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
# Already set in your step 3
plt.figure(figsize=(10,5))
sns.countplot(x='day_of_week', data=accidents, color='steelblue')
plt.title('Accidents by Day of Week')
plt.xlabel('Day')
plt.ylabel('Accident Count')
plt.xticks(rotation=45)
plt.show()

"""Most accidents happen on weekdays, especially Friday, because more people are commuting and traveling. Saturday and Sunday have fewer accidents, likely due to lighter traffic. This pattern shows that workdays carry higher accident risk than weekends.

### Accidents by Hour and Day of Week
"""

# Create pivot table of accident counts
hour_day = accidents.groupby(['hour', 'day_of_week']).size().unstack(fill_value=0)
weekday_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
hour_day = hour_day[weekday_order]

# Plot heatmap with annotations
plt.figure(figsize=(14,8))  # Larger figure to fit numbers
sns.heatmap(hour_day, annot=True, fmt='d', cmap='YlOrRd',
            cbar_kws={'label': 'Number of Accidents'})
plt.title('Accidents by Hour and Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Hour')
plt.show()

"""Accidents happen most often on weekdays during afternoon rush hours (3–6 PM), with Friday being the peak. Weekends have fewer accidents, but they are more spread out during the daytime. Early mornings (midnight to 5 AM) have the lowest accident counts every day. This pattern matches when people are most active on the roads.

### Accidents by Weekend vs Weekday
"""

# Why: Simple binary comparison to confirm weekday dominance.
plt.figure(figsize=(6,4))
sns.countplot(x='is_weekend', data=accidents, color='steelblue')
plt.title('Accidents: Weekend vs Weekday')
plt.xlabel('Is Weekend?')
plt.ylabel('Accident Count')
plt.xticks([0,1], ['Weekday', 'Weekend'])
plt.show()

"""This graph shows that weekdays have far more accidents than weekends – about three times higher. Weekend accidents are much lower because fewer people are commuting or traveling for work. This confirms that weekday traffic patterns create the highest risk.

### Accidents by Month
"""

plt.figure(figsize=(10,5))
order = range(1,13)
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
sns.countplot(x='month', data=accidents, order=order, color='steelblue')
plt.title('Accidents by Month')
plt.xlabel('Month')
plt.ylabel('Accident Count')
plt.xticks(ticks=range(12), labels=month_names, rotation=45)
plt.show()

"""The safest months are February and April when very few accidents happen. As the year goes on accidents keep rising and become the worst around September and October. The second half of the year is clearly more dangerous than the first half.

###  Accidents by Season
"""

plt.figure(figsize=(6,4))
sns.countplot(x='season', data=accidents, palette='Set2')
plt.title('Accidents by Season')
plt.show()

"""Accidents are more common in autumn months (September–November) and lowest in late winter/early spring (February–April). Summer months stay consistently high, likely due to more travel and better weather. This pattern shows that accident risk follows seasonal changes in traffic and road conditions.

### Accidents by Year
"""

# -------------------------------------------------
# 8. Accidents by Year
# -------------------------------------------------
# Why: Detect long‑term trends (increase or decrease over time).
years = accidents['accident_year'].value_counts().sort_index()
if len(years) > 1:
    plt.figure(figsize=(8,4))
    years.plot(kind='bar', color='steelblue')
    plt.title('Accidents by Year')
    plt.xlabel('Year')
    plt.ylabel('Accident Count')
    plt.xticks(rotation=0)
    plt.show()
    ''' Insight:
       - [Describe the trend: e.g., increasing from 2020 to 2022, then stable.]
       - Any anomaly (like a drop in 2020) may reflect external factors (e.g., COVID lockdowns).
    '''
else:
    print("Only one year in data – skipping yearly plot.")

"""Accidents increased from 2020 to 2022, then stayed mostly stable through 2024. The lower number in 2020 was likely due to COVID‑19 lockdowns reducing travel. Overall, accident numbers have remained steady in recent years.

### Accident by Month and Years
"""

# Ensure date column is datetime
accidents['date'] = pd.to_datetime(accidents['date'])

# Extract month and year
accidents['month'] = accidents['date'].dt.month
accidents['year'] = accidents['date'].dt.year

# Create a pivot table for heatmap
month_year_accidents = accidents.groupby(['month', 'year']).size().unstack(fill_value=0)

# Define month names for better readability
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
month_year_accidents.index = month_names[:len(month_year_accidents.index)]

plt.figure(figsize=(12, 8))
sns.heatmap(month_year_accidents, annot=True, fmt='d', cmap='YlGnBu',
            linewidths=.5, cbar_kws={'label': 'Number of Accidents'})
plt.title('Number of Accidents by Month and Year')
plt.xlabel('Year')
plt.ylabel('Month')
plt.show()

"""This heatmap shows accident counts for each month across multiple years. Darker blue means more accidents (9000+), lighter blue/green means fewer (4000–6000). The pattern shows that autumn months (September–November) tend to have more accidents each year, while early months like February and April often have fewer. There is also a noticeable drop in accidents during 2020 and 2021, likely due to COVID‑19 lockdowns, with numbers increasing again in later years.

### Rush Hour vs Non‑Rush Hour
"""

plt.figure(figsize=(6,4))
ax = sns.countplot(x='rush_hour', data=accidents, hue='rush_hour', palette='Set1', legend=False)
plt.title('Accidents: Rush Hour vs Non‑Rush Hour')
plt.xlabel('')
plt.ylabel('Accident Count')
plt.xticks([0,1], ['Non-Rush', 'Rush'])
# Add explanation of rush hour definition
plt.text(0.5, -0.2, 'Rush hour defined as 7–9 AM and 4–7 PM',
         transform=plt.gca().transAxes, ha='center', fontsize=9)
plt.show()

"""Rush hours (7–9 AM and 4–7 PM) have significantly more accidents than non‑rush hours. This shows that higher traffic volume during commuting times leads to more crashes. These are the busiest and riskiest times on the road.

### Trend Analysis – 7‑Day Rolling Average
"""

# -------------------------------------------------
# 9. 7‑Day Rolling Average of Daily Accidents
# -------------------------------------------------
# Goal: Smooth daily fluctuations to reveal long‑term trends and seasonality.


# Ensure date is datetime and set as index for easier plotting
accidents['date'] = pd.to_datetime(accidents['date'])
daily_acc = accidents.groupby('date').size()

# Calculate 7‑day rolling average
rolling_avg = daily_acc.rolling(window=7).mean()

# Plot
plt.figure(figsize=(14, 6))
plt.plot(rolling_avg.index, rolling_avg.values, color='red', linewidth=2)
plt.title('7‑Day Rolling Average of Daily Accidents', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Accidents (smoothed)', fontsize=12)
plt.grid(True, alpha=0.3)

# Add vertical lines for each year to mark boundaries
years = rolling_avg.index.year.unique()
for year in years:
    plt.axvline(pd.Timestamp(f'{year}-01-01'), color='gray', linestyle='--', alpha=0.5)

# Annotate a peak (e.g., the highest point)
max_idx = rolling_avg.idxmax()
plt.annotate(f'Peak: {rolling_avg.max():.0f} accidents/day',
             xy=(max_idx, rolling_avg.max()),
             xytext=(max_idx, rolling_avg.max() + 30),
             arrowprops=dict(arrowstyle='->', color='black'),
             ha='center', fontsize=10)

# Annotate a trough (e.g., the lowest point)
min_idx = rolling_avg.idxmin()
plt.annotate(f'Trough: {rolling_avg.min():.0f} accidents/day',
             xy=(min_idx, rolling_avg.min()),
             xytext=(min_idx, rolling_avg.min() - 50),
             arrowprops=dict(arrowstyle='->', color='black'),
             ha='center', fontsize=10)

# Format x‑axis to show years nicely
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.gca().xaxis.set_major_locator(mdates.YearLocator())
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""Daily accidents crashed to just 71 per day during early 2020 lockdowns when roads were nearly empty. Once life returned to normal, numbers climbed back up to around 250-330 accidents per day consistently. The most dangerous period was late 2023 when accidents spiked to a peak of 356 per day. Small dips appear at the start of each year likely due to holiday periods with less traffic. Sadly, accident numbers never really improved over 5 years and kept returning to the same high levels.

### Monthly Trend Across Years
"""

# Only proceed if there is more than one year of data
years_unique = accidents['accident_year'].nunique()
if years_unique > 1:
    # Create a year‑month column
    accidents['year_month'] = accidents['date'].dt.to_period('M')
    monthly = accidents.groupby('year_month').size()
    monthly.index = monthly.index.to_timestamp()  # convert to timestamp for plotting

    # Plot
    plt.figure(figsize=(14, 6))
    plt.plot(monthly.index, monthly.values, marker='o', linestyle='-',
             color='green', markersize=4, linewidth=1.5, markeredgecolor='darkgreen')
    plt.title('Monthly Accident Count', fontsize=14)
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Number of Accidents', fontsize=12)
    plt.grid(True, alpha=0.3)

    # Add vertical lines at the start of each year
    years = monthly.index.year.unique()
    for year in years:
        plt.axvline(pd.Timestamp(f'{year}-01-01'), color='gray',
                    linestyle='--', alpha=0.5, linewidth=1)

    # Annotate the highest month
    max_idx = monthly.idxmax()
    plt.annotate(f'Peak: {monthly.max():.0f}',
                 xy=(max_idx, monthly.max()),
                 xytext=(max_idx, monthly.max() + 5000),
                 arrowprops=dict(arrowstyle='->', color='black'),
                 ha='center', fontsize=10)

    # Annotate the lowest month
    min_idx = monthly.idxmin()
    plt.annotate(f'Trough: {monthly.min():.0f}',
                 xy=(min_idx, monthly.min()),
                 xytext=(min_idx, monthly.min() - 5000),
                 arrowprops=dict(arrowstyle='->', color='black'),
                 ha='center', fontsize=10)

    # Format x‑axis to show year and month clearly
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
    plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=6))  # label every 6 months
    plt.xticks(rotation=45)

    plt.tight_layout()
    plt.show()
else:
    print("Only one year of data – skipping monthly trend plot.")

"""Monthly accidents collapsed to around 3,000 in early 2020 due to COVID lockdowns, the lowest point across the entire period. Numbers then recovered strongly, reaching near 9,500-10,000 by late 2020 and 2021. From 2022 onwards, accidents stabilized between roughly 7,500 and 9,500 every month with a regular up-and-down pattern. There is a slight dip visible around mid-2024 dropping to about 7,500 but it recovered quickly. Overall the monthly counts remain consistently high with no real downward improvement over time.

# Temp 2

## Severity Analysis – How Serious Are Accidents?

In the severity analysis, we will examine how serious accidents are and what factors influence their severity. We will look at the overall distribution of slight, serious, and fatal accidents. Then we will explore how severity changes across different times, including by hour, day of week, month, and time of day. This will help identify when and where the most dangerous accidents occur.

### Overall Accident Severity Distribution
"""

# Count unique values
severity_counts = accidents['accident_severity'].value_counts()

plt.figure(figsize=(8,6))

# Create pie chart
wedges, texts, autotexts = plt.pie(
    severity_counts,
    autopct='%1.1f%%',
    startangle=90
)

# Create legend labels (Value + Count)
legend_labels = [
    f"{label} (Count: {count})"
    for label, count in zip(severity_counts.index, severity_counts.values)
]

plt.legend(
    wedges,
    legend_labels,
    title="Severity Levels",
    loc="center left",
    bbox_to_anchor=(1, 0.5)
)

plt.title('Accident Severity Distribution')
plt.axis('equal')  # Keeps pie circular
plt.tight_layout()
plt.show()

"""Most accidents are slight (76.4%), while serious accidents make up about one‑fifth (22.0%). Fatal accidents are very rare, only 1.5% of all cases. This shows that although most crashes are minor, a significant number still result in serious injuries.

### Severity by Hour (Casualty‑Level)
"""

# Ensure hour is integer
df_final['hour'] = df_final['hour'].astype(int)

plt.figure(figsize=(14,6))
sev_hour = df_final.groupby(['hour', 'accident_severity']).size().reset_index(name='count')
sns.barplot(x='hour', y='count', hue='accident_severity', data=sev_hour, palette='tab20')
plt.title('Casualties by Hour and Severity')
plt.xlabel('Hour')
plt.ylabel('Number of Casualties')
plt.legend(title='Severity')
plt.show()

"""Accidents causing slight injuries happen most often during afternoon rush hours (4–6 PM), when traffic is heaviest. Serious and fatal accidents are much fewer, but they peak later at night (10 PM–2 AM) when there are fewer cars on the road. This shows that while most crashes are minor during busy times, late‑night driving carries a higher risk of death or serious injury.

### Severity by Day of Week
"""

weekday_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
df_final['day_of_week'] = pd.Categorical(df_final['day_of_week'], categories=weekday_order, ordered=True)

plt.figure(figsize=(12,6))
sev_dow = df_final.groupby(['day_of_week', 'accident_severity'], observed=True).size().reset_index(name='count')
sns.barplot(x='day_of_week', y='count', hue='accident_severity', data=sev_dow, palette='Set2')
plt.title('Casualties by Day of Week and Severity')
plt.xlabel('Day')
plt.ylabel('Number of Casualties')
plt.legend(title='Severity')
plt.show()

"""Slight accidents are highest on weekdays, especially Friday, because more people are on the roads. Serious and fatal accidents are fewer but make up a larger share on weekends, when late‑night driving and higher speeds may play a role. This shows that while weekdays have more crashes overall, weekends are relatively more dangerous.

### Severity by Month
"""

# Ensure date is datetime
df_final['date'] = pd.to_datetime(df_final['date'])

# Extract numeric month (1–12)
df_final['month_num'] = df_final['date'].dt.month

# Now group by month_num and severity
sev_month = df_final.groupby(['month_num', 'accident_severity']).size().reset_index(name='count')

plt.figure(figsize=(12,6))
sns.barplot(x='month_num', y='count', hue='accident_severity', data=sev_month, palette='tab10')
plt.title('Severity by Month')
plt.xlabel('Month')
plt.ylabel('Number of Casualties')
plt.legend(title='Severity')
plt.show()

"""Slight accidents are consistently the most common type every month, following the same seasonal pattern as total accidents. Serious and fatal accidents are much fewer but also peak during summer and autumn months. This shows that accident severity generally follows traffic volume – more crashes overall mean more of every type.

### Severity by Time of Day
"""

time_order = ['Night', 'Morning', 'Afternoon', 'Evening']

# Define time_bin function again if it's not globally available or directly apply it
def time_bin(hour):
    if 0 <= hour < 6:
        return 'Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

# Create 'time_of_day' column in df_final
df_final['time_of_day'] = df_final['hour'].apply(time_bin)
df_final['time_of_day'] = pd.Categorical(df_final['time_of_day'], categories=time_order, ordered=True)

plt.figure(figsize=(10,6))
sev_time = df_final.groupby(['time_of_day', 'accident_severity'], observed=True).size().reset_index(name='count')
sns.barplot(x='time_of_day', y='count', hue='accident_severity', data=sev_time, palette='tab10')
plt.title('Casualties by Time of Day and Severity')
plt.xlabel('Time of Day')
plt.ylabel('Number of Casualties')
plt.legend(title='Severity')
plt.show()

"""Afternoon and evening have the highest number of casualties, mostly slight injuries, because traffic is heaviest during these times. Night has the fewest casualties overall, but a larger share of them are fatal or serious. This suggests that while fewer people drive at night, the risk of dying in a crash is much higher.

##  Demographic Analysis

In demographic analysis, we will identify who is affected in accidents. We will examine casualty types (driver, passenger, pedestrian) and how they vary by hour. This includes casualty class by hour, driver age by hour, and casualty sex by hour.

### Casualty Class Distribution
"""

plt.figure(figsize=(8,5))
sns.countplot(x='casualty_class', data=df_final, hue='casualty_class', palette='Set1', legend=False)
plt.title('Distribution of Casualty Class')
plt.xlabel('Casualty Class')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Drivers or riders are the largest group, making up over half of all casualties. Passengers are the second largest group, followed by pedestrians with the smallest share. This shows that people inside vehicles are most often hurt, but pedestrians are also a significant concern.

### Casualty Class by Hour
"""

plt.figure(figsize=(14,6))
class_hour = df_final.groupby(['hour', 'casualty_class'], observed=True).size().reset_index(name='count')
sns.barplot(x='hour', y='count', hue='casualty_class', data=class_hour, palette='tab10')
plt.title('Casualty Class by Hour of Day')
plt.xlabel('Hour')
plt.ylabel('Number of Casualties')
plt.legend(title='Casualty Class')
plt.show()

"""Drivers and riders make up the majority of casualties at every hour, with peaks during morning and afternoon rush hours. Passengers follow a similar pattern but in smaller numbers. Pedestrians are far fewer overall, but their counts rise during daytime and peak in the early evening (5–6 PM), showing increased risk when crossing roads after work.

### Casualty Age by Hour
"""

plt.figure(figsize=(14,6))
sns.boxplot(x='hour', y='casualty_age', data=df_final, hue='hour', palette='viridis', legend=False)
plt.title('Casualty Age by Hour')
plt.xlabel('Hour')
plt.ylabel('Age')
plt.show()

"""Young adults (ages 20–40) are the most common age group in accidents at all hours. Late at night, the casualties are mostly younger people. During the day, the age range is wider, including more older adults. This suggests younger drivers are more active—and at risk—during late-night hours.

### Driver Age by Hour
"""

plt.figure(figsize=(14,6))
sns.boxplot(x='hour', y='driver_age', data=drivers, palette='coolwarm')
plt.title('Driver Age by Hour')
plt.xlabel('Hour')
plt.ylabel('Driver Age')
plt.show()

"""### Casualty Sex by Hour"""

# Clean sex column
df_final['casualty_sex_clean'] = df_final['casualty_sex'].apply(lambda x: x if x in ['Male','Female'] else 'Other')
sex_hour = df_final.groupby(['hour','casualty_sex_clean'], observed=True).size().reset_index(name='count')
plt.figure(figsize=(14,6))
sns.barplot(x='hour', y='count', hue='casualty_sex_clean', data=sex_hour, palette='pastel')
plt.title('Casualty Sex by Hour')
plt.xlabel('Hour')
plt.ylabel('Number of Casualties')
plt.legend(title='Sex')
plt.show()

"""Young adults (ages 20–40) make up the majority of drivers in accidents at all times of day. During late‑night hours (10 PM–3 AM), the drivers involved are mostly younger, with very few older drivers. In contrast, daytime hours include a wider mix of ages, from young to elderly. This pattern indicates that younger drivers are more active and at higher risk during late‑night driving.

## Car Details Analysis (with Vehicle Type)

In the car details analysis, we will examine the types of vehicles involved in accidents. We will look at the overall distribution of vehicle types, then explore how vehicle involvement changes by hour of day and by day of week. This helps identify which vehicles are most common and when they are most at risk.

### Vehicle Type Distribution
"""

plt.figure(figsize=(12,6))
order = df_final['vehicle_type'].value_counts().index[:10]  # top 10
sns.countplot(x='vehicle_type', data=df_final, order=order,
              hue='vehicle_type', palette='tab20', legend=False)
plt.title('Top 10 Vehicle Types Involved in Casualties')
plt.xlabel('Vehicle Type')
plt.ylabel('Number of Casualties')
plt.xticks(rotation=45)
plt.show()

"""Cars are involved in the most casualties by far. Motorcycles and bicycles also appear often, showing vulnerable road users are at risk. Other vehicles like vans, taxis, and buses are much less common.

### Vehicle Type by Hour
"""

# Get top 10 vehicle types for clarity (re-defining as it might have been deleted)
top_vehicles = df_final['vehicle_type'].value_counts().index[:10]

veh_hour = df_final[df_final['vehicle_type'].isin(top_vehicles)].groupby(['hour','vehicle_type'], observed=True).size().reset_index(name='count')
plt.figure(figsize=(14,6))
sns.barplot(x='hour', y='count', hue='vehicle_type', data=veh_hour, palette='tab20')
plt.title('Vehicle Type by Hour')
plt.xlabel('Hour')
plt.ylabel('Number of Casualties')
plt.legend(bbox_to_anchor=(1.05,1))
plt.show()

"""### Vehicle Type by Day of Week"""

# Get top 10 vehicle types for clarity (re-defining as it might have been deleted)
top_vehicles = df_final['vehicle_type'].value_counts().index[:10]

veh_dow = df_final[df_final['vehicle_type'].isin(top_vehicles)].groupby(['day_of_week','vehicle_type'], observed=True).size().reset_index(name='count')
plt.figure(figsize=(12,6))
sns.barplot(x='day_of_week', y='count', hue='vehicle_type', data=veh_dow, palette='tab20')
plt.title('Vehicle Type by Day of Week')
plt.xlabel('Day')
plt.ylabel('Number of Casualties')
plt.legend(bbox_to_anchor=(1.05,1))
plt.show()

"""Cars dominate at every hour, with peaks during morning and afternoon rush hours. Motorcycles and bicycles are most common during daytime, especially in good weather. Goods vehicles and vans follow similar patterns but in smaller numbers. Buses, taxis, and other vehicles appear steadily throughout the day.

## Time × Location Analysis

We will now move to the final part of your analysis: Time × Location. This section combines temporal patterns with spatial attributes like road type, urban/rural area, speed limit, and accident locations using OS grid references. We'll create plots such as:

Accidents by hour and road type

Accidents by hour and urban/rural area

Speed limit by hour

A scatter map of accident locations

### Road Type by Hour (Accident‑Level)
"""

# Use accident‑level data for accurate accident counts
accidents = df_final.drop_duplicates(subset='accident_index').copy()

plt.figure(figsize=(14,6))
road_hour = accidents.groupby(['hour', 'road_type'], observed=True).size().reset_index(name='count')
sns.barplot(x='hour', y='count', hue='road_type', data=road_hour, palette='tab20')
plt.title('Accidents by Hour and Road Type')
plt.xlabel('Hour')
plt.ylabel('Number of Accidents')
plt.legend(bbox_to_anchor=(1.05, 1), title='Road Type')
plt.show()

"""Single carriageways have the most accidents at all hours, especially during afternoon rush hour. Dual carriageways follow a similar pattern but with fewer accidents. Roundabouts, slip roads, and one‑way streets have much lower numbers throughout the day. This shows that most accidents happen on regular single‑carriageway roads where traffic is heaviest.

###  Urban/Rural by Hour (Accident‑Level)
"""

plt.figure(figsize=(14,6))
urban_hour = accidents.groupby(['hour', 'urban_or_rural_area'], observed=True).size().reset_index(name='count')
sns.barplot(x='hour', y='count', hue='urban_or_rural_area', data=urban_hour, palette='coolwarm')
plt.title('Accidents by Hour and Urban/Rural Area')
plt.xlabel('Hour')
plt.ylabel('Number of Accidents')
plt.legend(title='Area')
plt.show()

"""Urban areas have far more accidents than rural areas at every hour, especially during daytime and rush hours. Rural accidents are much lower but follow a similar pattern, peaking in the afternoon. Unallocated areas have no recorded accidents. This shows that most accidents happen in cities and towns where traffic is heaviest.

### Speed Limit by Hour
"""

# Convert speed_limit to numeric (if not already)
accidents['speed_limit'] = pd.to_numeric(accidents['speed_limit'], errors='coerce')

# Compute average speed limit per hour
avg_speed_by_hour = accidents.groupby('hour')['speed_limit'].mean().reset_index()

# Plot bar chart
plt.figure(figsize=(14,6))
sns.barplot(x='hour', y='speed_limit', data=avg_speed_by_hour, palette='viridis')
plt.title('Average Speed Limit of Accident Locations by Hour')
plt.xlabel('Hour of the Day')
plt.ylabel('Average Speed Limit (mph)')
plt.xticks(range(0,24))  # ensure all hours are shown
plt.show()

"""The average speed limit at accident locations stays fairly steady between 35-40 mph throughout the day. It is slightly higher in the early morning hours (4-6 AM) when traffic is lighter. This suggests that most accidents happen on roads with similar speed limits, regardless of time.

### Accident Locations
"""

plt.figure(figsize=(10,8))
# Sample to avoid overplotting
sample = df_final.sample(min(50000, len(df_final)))
plt.scatter(sample['location_easting_osgr'], sample['location_northing_osgr'],
            alpha=0.1, s=1, c='red')
plt.title('Accident Locations (OS Grid Reference)')
plt.xlabel('Easting')
plt.ylabel('Northing')
plt.show()

"""The scatter plot shows that accident locations are spread widely across the region, with dense clusters in certain areas. Most accidents are concentrated in areas with higher populations and more roads. The pattern reflects that accidents happen where more people live and travel.

### Severity by Location
"""

plt.figure(figsize=(10,8))
sample = df_final.sample(min(50000, len(df_final)))
sc = plt.scatter(sample['location_easting_osgr'], sample['location_northing_osgr'],
                 c=sample['accident_severity'].astype('category').cat.codes,
                 alpha=0.3, s=1, cmap='Reds')
plt.colorbar(sc, ticks=[0,1,2], label='Severity (0=Slight,1=Serious,2=Fatal)')
plt.title('Accident Locations Coloured by Severity')
plt.xlabel('Easting')
plt.ylabel('Northing')
plt.show()

"""
The map shows accident locations across the region, with colors indicating severity. Most accidents (slight and serious) are concentrated in urban areas where traffic is heaviest. Fatal accidents (dark red) are spread more widely, including rural locations, suggesting higher speeds and fewer emergency services play a role. This highlights that while cities have more crashes, fatal accidents are more common in remote areas."""